
[rewrite_local]
^https:\/\/gate-obt\.nqf\.qq\.com\/prod\/ws url script-request-header https://raw.githubusercontent.com/JeffGu88/qx/refs/heads/main/qq-farm-code.js

[mitm]
hostname = gate-obt.nqf.qq.com
